import requests
from bs4 import BeautifulSoup
from colorama import init, Fore
import datetime
import urllib3
import os

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
init(autoreset=True)

print(Fore.GREEN + "="*85)
print("     🔥 Web Vulnerability Scanner - v2.0")
print("     Muhammad Haris | CEH | Portfolio Project")
print("="*85 + Fore.RESET)

def save_html_report(url, findings, basic_info):
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M")
    filename = f"scan_report_{timestamp}.html"
    
    html_content = f"""<!DOCTYPE html>
<html>
<head>
    <title>WebVulnScanner Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; background: #f4f4f4; }}
        .container {{ background: white; padding: 30px; border-radius: 10px; box-shadow: 0 0 15px rgba(0,0,0,0.1); max-width: 900px; margin: auto; }}
        h1 {{ color: #d32f2f; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ padding: 12px; border: 1px solid #ddd; text-align: left; }}
        th {{ background: #f0f0f0; }}
        .finding {{ color: #d32f2f; font-weight: bold; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🔥 Web Vulnerability Scan Report</h1>
        <p><strong>Target:</strong> {url}</p>
        <p><strong>Scan Date:</strong> {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        <p><strong>Scanner:</strong> v2.0 - Muhammad Haris</p>
        
        <h2>📋 Basic Information</h2>
        <table>
            <tr><th>Info</th><th>Value</th></tr>
    """
    
    for key, value in basic_info.items():
        html_content += f"<tr><td>{key}</td><td>{value}</td></tr>"
    
    html_content += """
        </table>
        
        <h2>🔍 Vulnerability Findings</h2>
    """
    
    if findings:
        for finding in findings:
            html_content += f'<p class="finding">⚠️ {finding}</p>'
    else:
        html_content += '<p style="color:green;">✅ No major issues detected in basic scan</p>'
    
    html_content += """
        <hr>
        <p><strong>Report generated by WebVulnScanner</strong><br>
        GitHub Portfolio Project - Muhammad Haris (CEH)</p>
    </div>
</body>
</html>
    """
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write(html_content)
    
    print(Fore.GREEN + f"[✓] HTML Report saved: {filename}" + Fore.RESET)

# Main scanning function (same as before, slightly cleaned)
def scan_website(url):
    print(Fore.YELLOW + f"\n[+] Starting scan on: {url}" + Fore.RESET)
    findings = []
    basic_info = {}
    
    try:
        if not url.startswith(("http://", "https://")):
            url = "http://" + url

        headers = {'User-Agent': 'Mozilla/5.0 (WebVulnScanner-v2.0)'}
        response = requests.get(url, headers=headers, timeout=10, verify=False)
        
        print(Fore.GREEN + f"[✓] Connected | Status: {response.status_code}" + Fore.RESET)
        
        soup = BeautifulSoup(response.text, 'html.parser')
        
        basic_info = {
            "Title": soup.title.string.strip()[:100] if soup.title else 'Not Found',
            "Server": response.headers.get('Server', 'Not Detected'),
            "Status Code": response.status_code,
            "Page Size": f"{len(response.text):,} characters"
        }
        
        print(Fore.CYAN + "\n📋 Basic Information:" + Fore.RESET)
        for key, value in basic_info.items():
            print(f"   {key}: {value}")
        
        print(Fore.CYAN + "\n🔍 Vulnerability Checks:" + Fore.RESET)
        text = response.text.lower()
        
        if any(x in text for x in ["sql syntax", "you have an error in your sql", "mysql_fetch", "syntax error"]):
            print(Fore.RED + "[!] Possible SQL Injection" + Fore.RESET)
            findings.append("SQL Injection Vulnerability")
        else:
            print(Fore.GREEN + "[✓] No obvious SQL Injection" + Fore.RESET)
        
        if any(x in text for x in ["<script>", "javascript:", "onerror=", "alert("]):
            print(Fore.RED + "[!] Possible XSS" + Fore.RESET)
            findings.append("Cross-Site Scripting (XSS)")
        else:
            print(Fore.GREEN + "[✓] No obvious XSS" + Fore.RESET)
        
        print(Fore.CYAN + "\n🔐 Security Headers:" + Fore.RESET)
        missing = [h for h in ['X-Frame-Options', 'X-XSS-Protection', 'Content-Security-Policy'] 
                  if h.lower() not in str(response.headers).lower()]
        if missing:
            print(Fore.RED + f"[!] Missing Security Headers: {missing}" + Fore.RESET)
            findings.append(f"Missing Security Headers: {missing}")
        else:
            print(Fore.GREEN + "[✓] Good security headers" + Fore.RESET)
        
        save_html_report(url, findings, basic_info)
        
    except Exception as e:
        print(Fore.RED + f"[✗] Error: {e}" + Fore.RESET)

# Menu
if __name__ == "__main__":
    while True:
        print(Fore.BLUE + "\n" + "="*50)
        print("               MAIN MENU")
        print("="*50)
        print("1. Start New Scan")
        print("2. Exit")
        print("="*50)
        
        choice = input(Fore.BLUE + "\nEnter choice (1/2): " + Fore.RESET).strip()
        
        if choice == "1":
            target = input(Fore.BLUE + "\nEnter target URL: " + Fore.RESET).strip()
            if target:
                scan_website(target)
        elif choice == "2":
            print(Fore.GREEN + "\nThank you for using WebVulnScanner! 🔥" + Fore.RESET)
            break