import requests
from bs4 import BeautifulSoup
from colorama import init, Fore
import datetime
import urllib3
import os
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
init(autoreset=True)

os.makedirs("reports", exist_ok=True)

print(Fore.GREEN + "="*110)
print("     🔥 WebVulnScanner PRO - v3.7")
print("     Beautiful Professional Security Scanner")
print("     Muhammad Haris | Certified Ethical Hacker (CEH)")
print("="*110 + Fore.RESET)

def save_pdf_report(url, findings, basic_info, tech, subdomains):
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M")
    filename = f"reports/scan_report_{timestamp}.pdf"
    
    doc = SimpleDocTemplate(filename, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    styles = getSampleStyleSheet()
    
    # Custom Beautiful Styles
    title_style = ParagraphStyle('CustomTitle', parent=styles['Heading1'], fontSize=26, textColor=colors.red, spaceAfter=30, alignment=1)
    heading_style = ParagraphStyle('CustomHeading', parent=styles['Heading2'], fontSize=16, textColor=colors.darkblue, spaceAfter=12, backColor=colors.lightblue)
    normal_style = ParagraphStyle('Normal', parent=styles['Normal'], fontSize=11, spaceAfter=8)
    finding_style = ParagraphStyle('Finding', parent=styles['Normal'], fontSize=11, textColor=colors.red, spaceAfter=8)
    
    story = []
    
    # Header
    story.append(Paragraph("WebVulnScanner PRO", title_style))
    story.append(Paragraph("<b>Security Assessment Report</b>", styles['Heading2']))
    story.append(Spacer(1, 20))
    
    story.append(Paragraph(f"<b>Target:</b> {url}", normal_style))
    story.append(Paragraph(f"<b>Date:</b> {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", normal_style))
    story.append(Spacer(1, 25))
    
    # Basic Information
    story.append(Paragraph("📋 Basic Information", heading_style))
    for key, value in basic_info.items():
        story.append(Paragraph(f"• <b>{key}:</b> {value}", normal_style))
    story.append(Spacer(1, 15))
    
    # Technologies
    story.append(Paragraph("🛠️ Technologies Detected", heading_style))
    story.append(Paragraph(f"• {', '.join(tech) if tech else 'Unknown'}", normal_style))
    story.append(Spacer(1, 15))
    
    # Subdomains
    story.append(Paragraph("🌐 Subdomains Discovered", heading_style))
    story.append(Paragraph(f"• Total Found: <b>{len(subdomains)}</b>", normal_style))
    if subdomains:
        for sub in subdomains[:8]:
            story.append(Paragraph(f"   - {sub}", normal_style))
    story.append(Spacer(1, 15))
    
    # Findings
    story.append(Paragraph("⚠️ Vulnerability Findings", heading_style))
    if findings:
        for finding in findings:
            story.append(Paragraph(f"🔴 {finding}", finding_style))
    else:
        story.append(Paragraph("🟢 No major vulnerabilities detected in this scan", normal_style))
    
    story.append(Spacer(1, 30))
    story.append(Paragraph("<b>Report generated by WebVulnScanner PRO</b>", normal_style))
    story.append(Paragraph("Muhammad Haris - Certified Ethical Hacker (CEH)", normal_style))
    
    doc.build(story)
    print(Fore.GREEN + f"[✓] Beautiful Colorful Report Saved: {filename}" + Fore.RESET)

# Rest of the functions (same as before)
def detect_technologies(response):
    tech = []
    text = response.text.lower()
    if "wordpress" in text or "wp-content" in text:
        tech.append("WordPress")
    if "php" in text:
        tech.append("PHP")
    if "cloudflare" in str(response.headers).lower():
        tech.append("Cloudflare")
    if "apache" in str(response.headers).lower():
        tech.append("Apache")
    return tech or ["Unknown"]

def check_wordpress(url):
    findings = []
    try:
        for path in ["/wp-login.php", "/wp-admin"]:
            if requests.get(url + path, timeout=8, verify=False).status_code in [200, 301]:
                findings.append(f"WordPress Panel Exposed → {url}{path}")
    except:
        pass
    return findings

def subdomain_enum(domain):
    print(Fore.CYAN + "\n🌐 Performing Subdomain Enumeration..." + Fore.RESET)
    subdomains = []
    clean_domain = domain.replace("http://", "").replace("https://", "").strip("/")
    
    common_subs = ["www", "admin", "cms", "dev", "test", "api", "mail", "ftp", "blog", "portal", "staging", "login"]
    
    for sub in common_subs:
        sub_url = f"http://{sub}.{clean_domain}"
        try:
            r = requests.get(sub_url, timeout=6, verify=False)
            if r.status_code in [200, 301, 302, 403]:
                print(Fore.GREEN + f"[+] Found: {sub_url}" + Fore.RESET)
                subdomains.append(sub_url)
        except:
            continue
    print(Fore.GREEN + f"[✓] Discovered {len(subdomains)} subdomains" + Fore.RESET)
    return subdomains

def advanced_scan(url):
    print(Fore.YELLOW + f"\n[+] Starting Full Professional Scan on: {url}" + Fore.RESET)
    findings = []
    tech = []
    basic_info = {}
    
    try:
        if not url.startswith(("http://", "https://")):
            url = "http://" + url

        headers = {'User-Agent': 'WebVulnScanner-PRO-v3.7'}
        response = requests.get(url, headers=headers, timeout=20, verify=False)
        
        print(Fore.GREEN + f"[✓] Connected | Status: {response.status_code}" + Fore.RESET)
        
        soup = BeautifulSoup(response.text, 'html.parser')
        
        basic_info = {
            "Title": soup.title.string.strip()[:100] if soup.title else 'Not Found',
            "Server": response.headers.get('Server', 'Not Detected'),
            "Status Code": response.status_code,
            "Page Size": f"{len(response.text):,} characters"
        }
        
        text = response.text.lower()
        tech = detect_technologies(response)
        
        if any(x in text for x in ["sql syntax", "mysql_fetch", "you have an error", "syntax error"]):
            findings.append("SQL Injection Vulnerability")
        if any(x in text for x in ["<script>", "javascript:", "onerror=", "alert("]):
            findings.append("XSS Vulnerability")
        
        missing = [h for h in ['X-Frame-Options', 'X-XSS-Protection', 'Content-Security-Policy'] 
                  if h.lower() not in str(response.headers).lower()]
        if missing:
            findings.append(f"Missing Security Headers: {missing}")
        
        findings.extend(check_wordpress(url))
        
        subdomains = subdomain_enum(url)
        
        save_pdf_report(url, findings, basic_info, tech, subdomains)
        
    except Exception as e:
        print(Fore.RED + f"[✗] Error: {e}" + Fore.RESET)

if __name__ == "__main__":
    while True:
        print(Fore.BLUE + "\n" + "="*75)
        print("              WebVulnScanner PRO v3.7")
        print("="*75)
        print("1. Start Full Professional Scan")
        print("2. Exit")
        print("="*75)
        
        choice = input(Fore.BLUE + "\nEnter choice (1/2): " + Fore.RESET).strip()
        
        if choice == "1":
            target = input(Fore.BLUE + "\nEnter target URL: " + Fore.RESET).strip()
            if target:
                advanced_scan(target)
        elif choice == "2":
            print(Fore.GREEN + "\nThank you for using WebVulnScanner PRO!" + Fore.RESET)
            break